<?php

/**
 * This file is part of the Hal library
 *
 * (c) Ben Longden <ben@nocarrier.co.uk
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package Nocarrier
 */

namespace Nocarrier;

use Nocarrier\HalLink;
use Nocarrier\HalLinkContainer;
use SimpleXMLElement;

/**
 * The Hal document class
 *
 * @package Nocarrier
 * @author Ben Longden <ben@nocarrier.co.uk>
 */
final class Hal
{
    /**
     * An array of embedded Hal objects representing embedded resources.
     * @var mixed[]
     */
    private array $resources = [];

    /**
     * A collection of \Nocarrier\HalLink objects keyed by the link relation to
     * this resource.
     *
     * array(
     *     'next' => [HalLink]
     * )
     *
     * @var array
     */
    private HalLinkContainer $links;

    /**
     * A list of rel types for links that will force a rel type to array for one element
     *
     * @var list<string>
     */
    private array $arrayLinkRels = [];

    /**
     * A list of rel types for links that will force a rel type to array for one element
     *
     * @var list<string>
     */
    private array $arrayResourceRels = [];

    /**
     * Whether xml attribute markers should be stripped when rendering
     */
    private bool $shouldStripAttributes = true;

    /**
     * Construct a new Hal object from an array of data. You can markup the
     * $data array with certain keys and values in order to affect the
     * generated JSON or XML documents if required to do so.
     *
     * '@' prefix on any array key will cause the value to be set as an
     * attribute on the XML element generated by the parent. i.e, array('x' =>
     * array('@href' => 'http://url')) will yield <x href='http://url'></x> in
     * the XML representation. The @ prefix will be stripped from the JSON
     * representation.
     *
     * Specifying the key 'value' will cause the value of this key to be set as
     * the value of the XML element instead of a child. i.e, array('x' =>
     * array('value' => 'example')) will yield <x>example</x> in the XML
     * representation. This will not affect the JSON representation.
     *
     * @param mixed $uri
     * @param array|Traversable $data
     *
     * @throws \RuntimeException
     */
    public function __construct(/**
         * The uri represented by this representation.
         */
        private $uri = null,
        private iterable $data = [],
    ) {
        $this->links = new HalLinkContainer();
    }

    /**
     * Decode a application/hal+json document into a Nocarrier\Hal object.
     */
    public static function fromJson(string $data, int $depth = 0): Hal
    {
        return JsonHalFactory::fromJson(new self(), $data, $depth);
    }

    /**
     * Decode a application/hal+xml document into a Nocarrier\Hal object.
     */
    public static function fromXml(string|SimpleXMLElement $data, int $depth = 0): Hal
    {
        return XmlHalFactory::fromXml(new self(), $data, $depth);
    }

    /**
     * Add a link to the resource, identified by $rel, located at $uri.
     *
     * @param array<string, string>|array<string, bool> $attributes
     *   Other attributes, as defined by HAL spec and RFC 5988.
     * @param bool $forceArray whether to force a rel to be an array if it has only one entry
     */
    public function addLink(string $rel, string $uri, array $attributes = [], bool $forceArray = false): self
    {
        return $this->addHalLink($rel, new HalLink($uri, $attributes), $forceArray);
    }

    /**
     * Add a link instance to the resource, identified by $rel.
     *
     * @param bool $forceArray whether to force a rel to be an array if it has only one entry
     */
    public function addHalLink(string $rel, HalLink $link, bool $forceArray = false): self
    {
        $this->links[$rel][] = $link;

        if ($forceArray) {
            $this->arrayLinkRels[] = $rel;
        }

        return $this;
    }

    /**
     * Add an embedded resource, identified by $rel and represented by $resource.
     */
    public function addResource(string $rel, Hal $resource = null, bool $forceArray = true): self
    {
        $this->resources[$rel][] = $resource;

        if ($forceArray) {
            $this->arrayResourceRels[] = $rel;
        }

        return $this;
    }

    /**
     * Set an embedded resource, identified by $rel and represented by $resource
     *
     * Using this method signifies that $rel will only ever be a single object
     * (only really relevant to JSON rendering)
     *
     * @param list<Hal>|Hal $resource
     */
    public function setResource(string $rel, array|Hal $resource): self
    {
        if (is_array($resource)) {
            foreach ($resource as $r) {
                $this->addResource($rel, $r);
            }

            return $this;
        }

        $this->resources[$rel][] = $resource;

        return $this;
    }

    /**
     * Set resource's data
     */
    public function setData(array $data = null): self
    {
        $this->data = $data;

        return $this;
    }

    /**
     * Return an array of data (key => value pairs) representing this resource.
     *
     * @param null|string data key
     * @return mixed Returns an array if no key is passed in, otherwise returns the data
     */
    public function getData($key = null)
    {
        if ($key) {
            return $this->data[$key] ?? [];
        }

        return $this->data;
    }

    /**
     * Return an array of Nocarrier\HalLink objects representing resources
     * related to this one.
     *
     * @return array A collection of \Nocarrier\HalLink
     */
    public function getLinks(): HalLinkContainer
    {
        return $this->links;
    }

    /**
     * Lookup and return an array of HalLink objects for a given relation.
     * Will also resolve CURIE rels if required.
     *
     * @return list<HalLink>|false
     *   Array of HalLink objects if found. Otherwise false.
     */
    public function getLink(string $rel): array|false
    {
        return $this->links->get($rel);
    }

    /**
     * Return an array of Nocarrier\Hal objected embedded in this one.
     * @return mixed[][]
     */
    public function getResources(): array
    {
        return array_map(
            fn($resource): array => is_array($resource) ? $resource : [$resource],
            $this->resources,
        );
    }

    /**
     * Return an array of Nocarrier\Hal objected embedded in this one.
     *
     * @return Hal
     */
    public function getResource($rel)
    {
        $resources = $this->getResources();

        return $resources[$rel] ?? null;
    }

    /**
     * Return an array of Nocarrier\Hal objected embedded in this one. Each key
     * may contain an array of resources, or a single resource. For a
     * consistent approach, use getResources
     *
     * @return mixed[]
     */
    public function getRawResources(): array
    {
        return $this->resources;
    }

    /**
     * Get the first resource for a given rel. Useful if you're only expecting
     * one resource, or you don't care about subsequent resources
     *
     * @return Hal
     */
    public function getFirstResource($rel)
    {
        $resource = $this->getResource($rel);

        if ($resource) {
            return $resource[0];
        }

        return null;
    }

    /**
     * Get the first link for a given rel. Useful if you're only expecting
     * one link, or you don't care about subsequent links
     *
     * @return HalLink
     */
    public function getFirstLink(string $rel): ?HalLink
    {
        $link = $this->getLink($rel);

        if ($link) {
            return $link[0];
        }

        return null;
    }

    /**
     * Set resource's URI
     */
    public function setUri($uri): self
    {
        $this->uri = $uri;

        return $this;
    }

    /**
     * Get resource's URI.
     *
     * @return mixed
     */
    public function getUri()
    {
        return $this->uri;
    }

    /**
     * Return the current object in a application/hal+json format (links and
     * resources).
     *
     * @param bool $pretty
     *   Enable pretty-printing.
     * @param bool $encode
     *   Run through json_encode
     * @return string|array
     */
    public function asJson(bool $pretty = false, bool $encode = true): string|array|false
    {
        $renderer = new HalJsonRenderer();

        return $renderer->render($this, $pretty, $encode);
    }

    /**
     * Return the current object in a application/hal+xml format (links and
     * resources).
     *
     * @param bool $pretty Enable pretty-printing
     * @return string
     */
    public function asXml(bool $pretty = false): string|false
    {
        $renderer = new HalXmlRenderer();

        return $renderer->render($this, $pretty);
    }

    /**
     * Create a CURIE link template, used for abbreviating custom link
     * relations.
     *
     * e.g,
     * $hal->addCurie('acme', 'http://.../rels/{rel}');
     * $hal->addLink('acme:test', 'http://.../test');
     */
    public function addCurie(string $name, string $uri): self
    {
        return $this->addLink('curies', $uri, ['name' => $name, 'templated' => true]);
    }

    /**
     * Get a list of rel types for links that will be forced to an array for one element
     * @return list<string>
     */
    public function getArrayLinkRels(): array
    {
        return $this->arrayLinkRels;
    }

    /**
     * Get a list of rel types for resources that will be forced to an array for one element
     * @return list<string>
     */
    public function getArrayResourceRels(): array
    {
        return $this->arrayResourceRels;
    }

    public function getShouldStripAttributes(): bool
    {
        return $this->shouldStripAttributes;
    }

    public function setShouldStripAttributes(bool $shouldStripAttributes): self
    {
        $this->shouldStripAttributes = $shouldStripAttributes;

        return $this;
    }
}
